## PYNQ Z2 constraints for the standalone RV32I pipeline demo
## Board part: xc7z020clg400-1

## 125 MHz PL clock
set_property -dict { PACKAGE_PIN H16 IOSTANDARD LVCMOS33 } [get_ports { clk }]
create_clock -add -name sys_clk_pin -period 8.000 -waveform {0.000 4.000} [get_ports { clk }]

## Active-high reset on pushbutton BTN0
set_property -dict { PACKAGE_PIN D19 IOSTANDARD LVCMOS33 } [get_ports { rst }]

## Board LEDs: heartbeat, running, pass, fail
set_property -dict { PACKAGE_PIN R14 IOSTANDARD LVCMOS33 } [get_ports { led[0] }]
set_property -dict { PACKAGE_PIN P14 IOSTANDARD LVCMOS33 } [get_ports { led[1] }]
set_property -dict { PACKAGE_PIN N16 IOSTANDARD LVCMOS33 } [get_ports { led[2] }]
set_property -dict { PACKAGE_PIN M14 IOSTANDARD LVCMOS33 } [get_ports { led[3] }]

## The 25 MHz CPU clock is generated by PLLE2_BASE in fpga_top.
## Vivado derives the generated PLL clock from sys_clk_pin for timing analysis.

## -----------------------------------------------------------------------
## UART via PYNQ-Z2 PMODA header (JA connector)
##   TX → JA1  (pin Y18)   connect to USB-UART adapter RX
##   RX → JA2  (pin Y19)   connect to USB-UART adapter TX
##   GND → JA5 or JA9      shared ground
## -----------------------------------------------------------------------
set_property -dict { PACKAGE_PIN Y18  IOSTANDARD LVCMOS33 } [get_ports { uart_txd }]
set_property -dict { PACKAGE_PIN Y19  IOSTANDARD LVCMOS33 } [get_ports { uart_rxd }]

## uart_rxd is asynchronous to sys_clk_pin – tell Vivado to ignore the path
set_false_path -from [get_ports { uart_rxd }]
