## PYNQ Z2 constraints for the standalone RV32I pipeline demo
## Board part: xc7z020clg400-1

## 125 MHz PL clock
set_property -dict { PACKAGE_PIN H16 IOSTANDARD LVCMOS33 } [get_ports { clk }]
create_clock -add -name sys_clk_pin -period 8.000 -waveform {0.000 4.000} [get_ports { clk }]

## Active-high reset on pushbutton BTN0
set_property -dict { PACKAGE_PIN D19 IOSTANDARD LVCMOS33 } [get_ports { rst }]

## Board LEDs: heartbeat, running, pass, fail
set_property -dict { PACKAGE_PIN R14 IOSTANDARD LVCMOS33 } [get_ports { led[0] }]
set_property -dict { PACKAGE_PIN P14 IOSTANDARD LVCMOS33 } [get_ports { led[1] }]
set_property -dict { PACKAGE_PIN N16 IOSTANDARD LVCMOS33 } [get_ports { led[2] }]
set_property -dict { PACKAGE_PIN M14 IOSTANDARD LVCMOS33 } [get_ports { led[3] }]

## The 25 MHz CPU clock is generated by PLLE2_BASE in fpga_top.
## Vivado derives the generated PLL clock from sys_clk_pin for timing analysis.

## -----------------------------------------------------------------------
## UART via PYNQ-Z2 PMODA header (JA connector)
##   TX → JA1  (pin Y18)   connect to USB-UART adapter RX
##   RX → JA2  (pin Y19)   connect to USB-UART adapter TX
##   GND → JA5 or JA9      shared ground
## -----------------------------------------------------------------------
set_property -dict { PACKAGE_PIN Y18  IOSTANDARD LVCMOS33 } [get_ports { uart_txd }]
set_property -dict { PACKAGE_PIN Y19  IOSTANDARD LVCMOS33 } [get_ports { uart_rxd }]

## uart_rxd is asynchronous to sys_clk_pin – tell Vivado to ignore the path
set_false_path -from [get_ports { uart_rxd }]

## Phase 12: Button input (BTN1 only — BTN0 is already rst)
## TODO — verify D20 is BTN1 on your specific PYNQ-Z2 board revision
set_property -dict { PACKAGE_PIN D20 IOSTANDARD LVCMOS33 } [get_ports { raw_btn_board }]
## raw_btn[0] tied to 0 internally in fpga_top (BTN0 reserved for rst) — no XDC entry needed

## Phase 12: Slide switch inputs
## TODO — verify A20 = SW0, B20 = SW1 on your board
set_property -dict { PACKAGE_PIN A20 IOSTANDARD LVCMOS33 } [get_ports { raw_sw[0] }]
set_property -dict { PACKAGE_PIN B20 IOSTANDARD LVCMOS33 } [get_ports { raw_sw[1] }]

## Phase 12: PWM output — PMODA JA3
## TODO — verify W18 is JA3 and is unused on your board
set_property -dict { PACKAGE_PIN W18 IOSTANDARD LVCMOS33 } [get_ports { pwm_out }]

## Async inputs — tell timing engine to ignore setup/hold on these paths
set_false_path -from [get_ports { raw_btn_board }]
set_false_path -from [get_ports { raw_sw[*] }]
